### ISSUE TITLE
The reclaim all button fails with extremely small amounts

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-wallet-ext#165] opened 2021-12-02 16:25 UTC
Due to how the web wallet implements reclaimEscrow transactions, it is possible to get stuck with a delegation for an extremely tiny amount (eg: 1.0*10^e-9).  Attempting to use the extension wallet to resolve this does not work despite trying to use the "ALL" button.

The error received is "The format of the amount you entered is incorrect...." because it is unhappy that I am trying to undelegate 0.00 from an available 0.

The ALL button should support undelegating extremely tiny amounts,so it is possible to fix delegations that are stuck this way.

I get that there is a nice human conversion between shares and ROSE, but the "ALL" button, should allow people to reclaim "ALL", and not be limited to "sensible" ROSE denominations.

**Comment by lukaw3d** [comment] 2022-08-05 00:02
I can't reproduce. My ALL button worked for 51 shares (0.000000051 gigashares)

**Comment by tjanez** [comment] 2022-09-22 11:21
Let's close this if someone encounters it again, we'll re-open.

**Closed by tjanez** 2022-09-22 11:21 UTC
Labels: bug
